apiVersion: v1
kind: Pod
metadata:
  name: pod1-page2
  labels:
    app: p2-svc
spec:
  nodeName: k8s-worker2
  containers:
  - name: nginx
    image: nginx:1.14.0
    ports:
    - containerPort: 8082
